# Generated by Django 2.2.1 on 2019-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.IntegerField(choices=[(0, '学士(取得予定)'), (1, '学士'), (2, '修士'), (3, '博士'), (4, '短期大学士'), (5, '専門士'), (6, '高度専門士')], default=0, verbose_name='学位'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(default='gmail', max_length=255, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(default=3, verbose_name='学年'),
        ),
        migrations.AddField(
            model_name='profile',
            name='highschool',
            field=models.CharField(blank=True, default='高校', max_length=20, verbose_name='高校名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='memo',
            field=models.TextField(default='なし', null=True, verbose_name='備考欄'),
        ),
    ]
