# Generated by Django 2.2.1 on 2019-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qboard', '0002_auto_20190906_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='インターン名')),
            ],
            options={
                'verbose_name': 'インターン名前情報データ',
                'verbose_name_plural': 'インターン名前情報データ',
            },
        ),
        migrations.CreateModel(
            name='Superman',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('skill', models.CharField(max_length=20, verbose_name='系統')),
                ('twitter', models.CharField(max_length=20, verbose_name='Twitterアカウント')),
                ('url', models.TextField(verbose_name='URL')),
                ('intern_name', models.ManyToManyField(to='qboard.InternName')),
            ],
            options={
                'verbose_name': 'すごい人情報データ',
                'verbose_name_plural': 'すごい人情報データ',
            },
        ),
    ]
