# Generated by Django 2.2.1 on 2019-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qboard', '0005_superman_twitter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_tag', models.CharField(max_length=20, verbose_name='スキルタグ名')),
            ],
            options={
                'verbose_name': 'スキルタグ情報データ',
                'verbose_name_plural': 'スキルタグ情報データ',
            },
        ),
    ]
