# Generated by Django 2.2.1 on 2019-09-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qboard', '0006_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='superman',
            name='skill',
        ),
        migrations.AddField(
            model_name='superman',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='qboard.Skill', verbose_name='系統'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('twitter_name', models.CharField(max_length=20, null=True, verbose_name='ホームページ用')),
                ('twitter', models.CharField(max_length=20, verbose_name='Twitterアカウント')),
                ('url', models.TextField(verbose_name='URL')),
                ('memo', models.TextField(verbose_name='理由、備考欄')),
                ('intern_name', models.ManyToManyField(blank=True, to='qboard.InternName', verbose_name='インターン名')),
                ('skill_tag', models.ManyToManyField(blank=True, null=True, to='qboard.Skill', verbose_name='系統')),
            ],
            options={
                'verbose_name': 'すごい人候補情報データ',
                'verbose_name_plural': 'すごい人候補情報データ',
            },
        ),
    ]
