# Generated by Django 2.2.1 on 2019-09-11 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qboard', '0007_auto_20190911_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='開発物url'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.TextField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='superman',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='開発物url'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skill_tag',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qboard.Skill', verbose_name='系統'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='インターン体験記url'),
        ),
        migrations.RemoveField(
            model_name='superman',
            name='skill',
        ),
        migrations.AddField(
            model_name='superman',
            name='skill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qboard.Skill', verbose_name='系統'),
        ),
        migrations.AlterField(
            model_name='superman',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='インターン体験記url'),
        ),
    ]
