# Generated by Django 2.2.1 on 2019-09-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qboard', '0008_auto_20190911_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skill_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qboard.Skill', verbose_name='系統'),
        ),
        migrations.AlterField(
            model_name='superman',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qboard.Skill', verbose_name='系統'),
        ),
    ]
