# Generated by Django 2.2.1 on 2019-09-12 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qboard', '0010_predict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='intern_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='intern_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qboard.InternName', verbose_name='インターン名'),
        ),
    ]
