# Generated by Django 2.2.1 on 2019-12-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qboard', '0012_intern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(default='学科', max_length=40, verbose_name='学科'),
        ),
    ]
